### ISSUE TITLE
Add annovar cmd (non-cavatica)

### ISSUE THREAD

**Issue by naqvia** [diskin-lab-chop/pathogenicity-assessment#18]
Add instructions on how to run annovar with correct flags in `README.md` to get correct vcf coordinates for downstream analyses.

**Comment by jungkim2** [comment]
perl table_annovar.pl input/test_hg38_selected_VEP_annotated.vcf hg38 --buildver hg38 --out test_hg38_selected --remove --protocol gnomad211_exome,gnomad211_genome --operation f,f --vcfinput
